import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

const minecraftFont = localFont({
  src: [
    {
      path: '../../public/fonts/MinecraftRegular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/MinecraftItalic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../../public/fonts/MinecraftBold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/MinecraftBoldItalic.woff2',
      weight: '700',
      style: 'italic',
    },
  ],
});

const departureMonoFont = localFont({
  src: [
    {
      path: '../../public/fonts/DepartureMono-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
      </head>
      <body className={`pico ${minecraftFont.className} ${departureMonoFont.className}`}>
        {children}
      </body>
    </html>
  );
}
